-- Insertion des espèces (id_espece is AUTOINCREMENT)
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ABI', 'Sapin', 'Abies');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ABICON', 'Sapin du Colorado', 'Abies concolor');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ABIGLA', 'Sapin glauque', 'Abies glauca');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ABILASari', 'Sapin des Alpes (variété/cultivar ''ari'')', 'Abies lasiocarpa ''ari''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ABINOR', 'Sapin du Caucase', 'Abies nordmanniana');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ABINUM', 'Sapin de Numidie', 'Abies numidica');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACE', 'Érable', 'Acer');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACECAM', 'Érable champêtre', 'Acer campestre');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACECAMele', 'Érable champêtre (variété/cultivar ''ele'')', 'Acer campestre ''ele''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACECAMels', 'Érable champêtre (variété/cultivar ''els'')', 'Acer campestre ''els''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACECAMred', 'Érable champêtre (variété/cultivar ''red'')', 'Acer campestre ''red''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACECAMros', 'Érable champêtre (variété/cultivar ''ros'')', 'Acer campestre ''ros''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACECAP', 'Érable Marsault', 'Acer caprea');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACEDAV', 'Érable', 'Acer (dav)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACENEG', 'Érable negundo', 'Acer negundo');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACENEGkel', 'Érable negundo (variété/cultivar ''kel'')', 'Acer negundo ''kel''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACENEGvar', 'Érable negundo (variété/cultivar ''var'')', 'Acer negundo ''var''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACEPAL', 'Érable du Japon', 'Acer palmatum');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACEPLA', 'Érable plane', 'Acer platanoides');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACEPLAcol', 'Érable plane (variété/cultivar ''col'')', 'Acer platanoides ''col''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACEPLAcri', 'Érable plane (variété/cultivar ''cri'')', 'Acer platanoides ''cri''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACEPLAfai', 'Érable plane (variété/cultivar ''fai'')', 'Acer platanoides ''fai''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACEPLApur', 'Érable plane (variété pourpre)', 'Acer platanoides f. purpurea/atropurpurea');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACEPSE', 'Érable sycomore', 'Acer pseudoplatanus');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACEPSEatr', 'Érable sycomore (variété pourpre)', 'Acer pseudoplatanus f. purpurea/atropurpurea');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACEPSEleo', 'Érable sycomore (variété/cultivar ''leo'')', 'Acer pseudoplatanus ''leo''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACERUB', 'Érable rouge', 'Acer rubra');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACESAC', 'Érable argenté', 'Acer saccharinum');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ACESACwie', 'Érable argenté (variété/cultivar ''wie'')', 'Acer saccharinum ''wie''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('AESARNaut', 'Marronnier (variété/cultivar ''aut'')', 'Aesculus (arn) ''aut''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('AESCAR', 'Marronnier rouge', 'Aesculus carnea');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('AESHIP', 'Marronnier commun', 'Aesculus hippocastanum');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('AEShom', 'Marronnier', 'Aesculus (hom)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('AILALT', 'Ailante glanduleux', 'Ailanthus altissima');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ALBJUL', 'Arbre de soie de Constantinople', 'Albizia julibrissin');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ALBJULcho', 'Arbre de soie de Constantinople (variété/cultivar ''cho'')', 'Albizia julibrissin ''cho''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ALNCOR', 'Aulne à petites feuilles (ou cordiforme)', 'Alnus cordata');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ALNGLU', 'Aulne glutineux', 'Alnus glutinosa');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ALNGLUimp', 'Aulne glutineux (variété/cultivar ''imp'')', 'Alnus glutinosa ''imp''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ALNSPA', 'Aulne', 'Alnus (spa)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('AMELAM', 'Amélanchier', 'Amelanchier (lam)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('BETPAP', 'Bouleau à papier', 'Betula papyrifera');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('BETPEN', 'Bouleau pleureur / verruqueux', 'Betula pendula');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('BETPENyou', 'Bouleau pleureur / verruqueux (variété/cultivar ''you'')', 'Betula pendula ''you''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('BETUTI', 'Bouleau de l''Himalaya', 'Betula utilis');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('BETUTIjac', 'Bouleau de l''Himalaya (variété/cultivar ''jac'')', 'Betula utilis ''jac''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('BUXSEM', 'Buis commun (toujours vert)', 'Buxus sempervirens');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CARBET', 'Charme commun', 'Carpinus betulus');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CARBETfas', 'Charme commun (port fastigié/colonnaire)', 'Carpinus betulus f. fastigiata');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CASSAT', 'Châtaignier commun', 'Castanea sativa');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CATBIG', 'Catalpa commun', 'Catalpa bignonioides');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CATBUN', 'Catalpa de Bunge', 'Catalpa bungei');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CEDATL', 'Cèdre de l''Atlas', 'Cedrus atlantica');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CEDATLgla', 'Cèdre de l''Atlas (variété/cultivar ''gla'')', 'Cedrus atlantica ''gla''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CEDATLpen', 'Cèdre de l''Atlas (port pleureur)', 'Cedrus atlantica f. pendula');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CEDDEO', 'Cèdre de l''Himalaya', 'Cedrus deodara');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CEDLIB', 'Cèdre du Liban', 'Cedrus libani');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CERSIL', 'Arbre de Judée de Judée', 'Cercis siliquastrum');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CHALAW', 'Faux-cyprès de Lawson', 'Chamaecyparis lawsoniana');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CHALAWgol', 'Faux-cyprès de Lawson (feuillage doré)', 'Chamaecyparis lawsoniana f. aurea');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CHANOO', 'Faux-cyprès', 'Chamaecyparis (noo)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CORAVE', 'Noisetier commun', 'Corylus avellana');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CORCOL', 'Noisetier', 'Corylus (col)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CORKOU', 'Noisetier', 'Corylus (kou)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CRALAEpau', 'Aubépine (variété/cultivar ''pau'')', 'Crataegus (lae) ''pau''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CRAMON', 'Aubépine à un style', 'Crataegus monogyna');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CRYJAP', 'Cryptoméria du Japon', 'Cryptomeria japonica');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CUP', 'Cyprès (espèce à définir)', 'Cupressus (sp.)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CUPARI', 'Cyprès (espèce à définir)', 'Cupressus (sp.)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CUPARIgla', 'Cyprès (espèce à définir)', 'Cupressus (sp.)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CUPLEY', 'Cyprès de Leyland', 'Cupressocyparis leylandii');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CUPLEYvar', 'Cyprès de Leyland', 'Cupressocyparis leylandii');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CUPSEM', 'Cyprès (espèce à définir)', 'Cupressus (sp.)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CUPfas', 'Cyprès (espèce à définir)', 'Cupressus (sp.)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('CYDVULbou', 'Cognassier (variété/cultivar ''bou'')', 'Cydonia (vul) ''bou''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ELAANG', 'Chalef à feuilles étroites', 'Elaeagnus angustifolia');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FAGSYL', 'Hêtre des bois', 'Fagus sylvatica');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FAGSYLdawgol', 'Hêtre des bois (variété/cultivar ''dawgol'')', 'Fagus sylvatica ''dawgol''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FAGSYLdawpur', 'Hêtre des bois (variété/cultivar ''dawpur'')', 'Fagus sylvatica ''dawpur''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FAGSYLfas', 'Hêtre des bois (port fastigié/colonnaire)', 'Fagus sylvatica f. fastigiata');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FAGSYLfaspur', 'Hêtre des bois (variété/cultivar ''faspur'')', 'Fagus sylvatica ''faspur''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FAGSYLpen', 'Hêtre des bois (port pleureur)', 'Fagus sylvatica f. pendula');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FAGSYLpur', 'Hêtre des bois (variété pourpre)', 'Fagus sylvatica f. purpurea/atropurpurea');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FRAAME', 'Frêne d''Amérique', 'Fraxinus americana');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FRAANG', 'Frêne à feuilles étroites', 'Fraxinus angustifolia');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FRAANGray', 'Frêne à feuilles étroites (variété/cultivar ''ray'')', 'Fraxinus angustifolia ''ray''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FRAEXC', 'Frêne commun', 'Fraxinus excelsior');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FRAEXCpen', 'Frêne commun (port pleureur)', 'Fraxinus excelsior f. pendula');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FRAORN', 'Frêne à fleurs', 'Fraxinus ornus');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FRAPEN', 'Frêne pleureur / verruqueux', 'Fraxinus pendula');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('FRAPENcim', 'Frêne pleureur / verruqueux (variété/cultivar ''cim'')', 'Fraxinus pendula ''cim''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('GINBIL', 'Ginkgo aux quarante écus', 'Ginkgo biloba');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('GLETRI', 'Févier d''Amérique', 'Gleditsia triacanthos');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('GLETRIine', 'Févier d''Amérique (variété/cultivar ''ine'')', 'Gleditsia triacanthos ''ine''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('GLETRIsun', 'Févier d''Amérique (variété/cultivar ''sun'')', 'Gleditsia triacanthos ''sun''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ILEAQU', 'Houx commun', 'Ilex aquifolium');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('JUGREG', 'Noyer commun', 'Juglans regia');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('JUNMEDpfi', 'JUN (variété/cultivar ''pfi'')', 'JUN (med) ''pfi''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('KOEPAN', 'Savonnier paniculé', 'Koelreuteria paniculata');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('KOEPANfas', 'Savonnier paniculé (port fastigié/colonnaire)', 'Koelreuteria paniculata f. fastigiata');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('LABANA', 'Cytise à grappes', 'Laburnum anagyroides');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('LAGIND', 'LAGIND', 'LAG (ind)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('LARDEC', 'LARDEC', 'LAR (dec)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('LIQSTY', 'Copalme d''Amérique', 'Liquidambar styraciflua');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('LIQSTYsil', 'Copalme d''Amérique (variété/cultivar ''sil'')', 'Liquidambar styraciflua ''sil''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('LIQSTYsle', 'Copalme d''Amérique (variété/cultivar ''sle'')', 'Liquidambar styraciflua ''sle''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('LIQSTYwor', 'Copalme d''Amérique (variété/cultivar ''wor'')', 'Liquidambar styraciflua ''wor''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('LIRTUL', 'Tulipier de Virginie', 'Liriodendron tulipifera');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MAGGRA', 'Magnolia', 'Magnolia (gra)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MAGKOB', 'Magnolia', 'Magnolia (kob)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MAGSOU', 'Magnolia de Soulange', 'Magnolia soulangeana');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MAGSOUhea', 'Magnolia de Soulange (variété/cultivar ''hea'')', 'Magnolia soulangeana ''hea''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MAL', 'Pommier', 'Malus');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALBAC', 'Pommier commun', 'Malus baccata');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALCOM', 'Pommier', 'Malus (com)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALCOMgol', 'Pommier (feuillage doré)', 'Malus (com) f. aurea');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALCOMtra', 'Pommier (variété/cultivar ''tra'')', 'Malus (com) ''tra''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALDOM', 'Pommier commun', 'Malus domestica');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALDOMast', 'Pommier commun (variété/cultivar ''ast'')', 'Malus domestica ''ast''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALDOMbel', 'Pommier commun (variété/cultivar ''bel'')', 'Malus domestica ''bel''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALDOMbos', 'Pommier commun (variété/cultivar ''bos'')', 'Malus domestica ''bos''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALDOMcal', 'Pommier commun (variété/cultivar ''cal'')', 'Malus domestica ''cal''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALDOMcox', 'Pommier commun (variété/cultivar ''cox'')', 'Malus domestica ''cox''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALDOMgra', 'Pommier commun (variété/cultivar ''gra'')', 'Malus domestica ''gra''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALDOMmel', 'Pommier commun (variété/cultivar ''mel'')', 'Malus domestica ''mel''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALDOMrei', 'Pommier commun (variété/cultivar ''rei'')', 'Malus domestica ''rei''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALPEN', 'Pommier pleureur / verruqueux', 'Malus pendula');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALPEReve', 'Pommier de Perse (variété/cultivar ''eve'')', 'Malus persica ''eve''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALTOR', 'Pommier', 'Malus (tor)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALTOR1', 'Pommier (variété/cultivar ''1'')', 'Malus (tor) ''1''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALTORbro', 'Pommier (variété/cultivar ''bro'')', 'Malus (tor) ''bro''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALTRI', 'Pommier d''Amérique', 'Malus triacanthos');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALTSC', 'Pommier', 'Malus (tsc)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALgol', 'Pommier', 'Malus (gol)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('MALred', 'Pommier', 'Malus (red)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('METGLY', 'Métaséquoia du Sichuan', 'Metasequoia glyptostroboides');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('NOTANT', 'NOTANT', 'NOT (ant)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PARPER', 'Parrotie de Perse', 'Parrotia persica');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PARPERvan', 'Parrotie de Perse (variété/cultivar ''van'')', 'Parrotia persica ''van''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PAUTOM', 'Paulownia argenté', 'Paulownia tomentosa');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PICABI', 'Épicéa commun', 'Picea abies');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PINNIGlar', 'Pin noir (variété/cultivar ''lar'')', 'Pinus nigra ''lar''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PINNIGnig', 'Pin noir (sous-espèce nig)', 'Pinus nigra subsp. nig');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PINSYL', 'Pin des bois', 'Pinus sylvatica');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PINWAL', 'Pin', 'Pinus (wal)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PLAACE', 'Platane commun', 'Platanus x acerifolia');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('POPALB', 'Peuplier blanc', 'Populus alba');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('POPCAN', 'Peuplier', 'Populus (can)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('POPEURrob', 'Peuplier (variété/cultivar ''rob'')', 'Populus (eur) ''rob''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('POPNIG', 'Peuplier noir', 'Populus nigra');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('POPNIGita', 'Peuplier noir d''Italie', 'Populus nigra ''Italica''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('POPSIM', 'Peuplier', 'Populus (sim)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('POPTRE', 'Peuplier tremble', 'Populus tremula');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRU', 'Cerisier/Prunier', 'Prunus');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUAVI', 'Cerisier/Prunier des oiseaux (Merisier)', 'Prunus avium');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUAVIbea', 'Cerisier/Prunier des oiseaux (Merisier) (variété/cultivar ''bea'')', 'Prunus avium ''bea''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUAVIbig', 'Cerisier/Prunier des oiseaux (Merisier) (variété/cultivar ''big'')', 'Prunus avium ''big''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUAVImar', 'Cerisier/Prunier des oiseaux (Merisier) (variété/cultivar ''mar'')', 'Prunus avium ''mar''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUCER', 'Cerisier/Prunier myrobolan', 'Prunus cerasifera');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUCERbig', 'Cerisier/Prunier myrobolan (variété/cultivar ''big'')', 'Prunus cerasifera ''big''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUCERbig1', 'Cerisier/Prunier myrobolan (variété/cultivar ''big1'')', 'Prunus cerasifera ''big1''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUCERbig2', 'Cerisier/Prunier myrobolan (variété/cultivar ''big2'')', 'Prunus cerasifera ''big2''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUCERcoe', 'Cerisier/Prunier myrobolan (variété/cultivar ''coe'')', 'Prunus cerasifera ''coe''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUCERpis', 'Cerisier/Prunier myrobolan (variété/cultivar ''pis'')', 'Prunus cerasifera ''pis''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUDOM', 'Cerisier/Prunier commun', 'Prunus domestica');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUDOMals', 'Cerisier/Prunier commun (variété/cultivar ''als'')', 'Prunus domestica ''als''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUDOMcha', 'Cerisier/Prunier commun (variété/cultivar ''cha'')', 'Prunus domestica ''cha''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUDOMmir', 'Cerisier/Prunier commun (variété/cultivar ''mir'')', 'Prunus domestica ''mir''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUDOMmon', 'Cerisier/Prunier commun (variété/cultivar ''mon'')', 'Prunus domestica ''mon''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUDOMrei', 'Cerisier/Prunier commun (variété/cultivar ''rei'')', 'Prunus domestica ''rei''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUDOMrei1', 'Cerisier/Prunier commun (variété/cultivar ''rei1'')', 'Prunus domestica ''rei1''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUDOMrei2', 'Cerisier/Prunier commun (variété/cultivar ''rei2'')', 'Prunus domestica ''rei2''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUDOMrei3', 'Cerisier/Prunier commun (variété/cultivar ''rei3'')', 'Prunus domestica ''rei3''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRULAU', 'Cerisier/Prunier', 'Prunus (lau)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUMAAamb', 'Cerisier/Prunier (variété/cultivar ''amb'')', 'Prunus (maa) ''amb''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUPERnuc', 'Cerisier/Prunier de Perse (variété/cultivar ''nuc'')', 'Prunus persica ''nuc''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUSER', 'Cerisier/Prunier du Japon', 'Prunus serrulata');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUSERama', 'Cerisier/Prunier du Japon (variété/cultivar ''ama'')', 'Prunus serrulata ''ama''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUSERfas', 'Cerisier/Prunier du Japon (port fastigié/colonnaire)', 'Prunus serrulata f. fastigiata');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUSERkan', 'Cerisier/Prunier du Japon (variété/cultivar ''kan'')', 'Prunus serrulata ''kan''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUSERpen', 'Cerisier/Prunier du Japon (port pleureur)', 'Prunus serrulata f. pendula');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUSERsun', 'Cerisier/Prunier du Japon (variété/cultivar ''sun'')', 'Prunus serrulata ''sun''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PRUSUBaut', 'Cerisier/Prunier (variété/cultivar ''aut'')', 'Prunus (sub) ''aut''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PSEMEN', 'PSEMEN', 'PSE (men)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PYRCAL', 'Poirier de Chine', 'Pyrus calleryana');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PYRCALcha', 'Poirier de Chine (variété/cultivar ''cha'')', 'Pyrus calleryana ''cha''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PYRCOM', 'Poirier', 'Pyrus (com)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PYRCOMcon', 'Poirier (variété/cultivar ''con'')', 'Pyrus (com) ''con''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('PYRCOMdoy', 'Poirier (variété/cultivar ''doy'')', 'Pyrus (com) ''doy''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('QUEBIC', 'Chêne', 'Quercus (bic)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('QUECAS', 'Chêne à feuilles de châtaignier', 'Quercus castaneifolia');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('QUECER', 'Chêne myrobolan', 'Quercus cerasifera');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('QUECOC', 'Chêne', 'Quercus (coc)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('QUEELL', 'Chêne', 'Quercus (ell)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('QUEILE', 'Chêne vert', 'Quercus ilex');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('QUEMAC', 'Chêne à gros fruits', 'Quercus macrocarpa');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('QUEPAL', 'Chêne du Japon', 'Quercus palmatum');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('QUEPET', 'Chêne', 'Quercus (pet)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('QUEROB', 'Chêne pédonculé', 'Quercus robur');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('QUEROBfas', 'Chêne pédonculé (port fastigié/colonnaire)', 'Quercus robur f. fastigiata');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('QUERUB', 'Chêne rouge', 'Quercus rubra');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('QUESHU', 'Chêne', 'Quercus (shu)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('RHUTYP', 'RHUTYP', 'RHU (typ)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ROBPSE', 'Robinier sycomore', 'Robinia pseudoplatanus');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ROBPSEfri', 'Robinier sycomore (variété/cultivar ''fri'')', 'Robinia pseudoplatanus ''fri''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SALALB', 'Saule blanc', 'Salix alba');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SALALBche', 'Saule blanc (variété/cultivar ''che'')', 'Salix alba ''che''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SALBAB', 'Saule pleureur', 'Salix babylonica');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SALCAP', 'Saule Marsault', 'Salix caprea');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SAMNIG', 'SAM noir', 'SAM nigra');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SEQGIG', 'Séquoia géant', 'Sequoiadendron giganteum');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SOPJAP', 'Sophora du Japon', 'Sophora japonica');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SOPJAPpen', 'Sophora du Japon (port pleureur)', 'Sophora japonica f. pendula');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SORALB', 'Sorbier/Alisier blanc', 'Sorbus alba');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SORARI', 'Sorbier/Alisier de l''Arizona', 'Sorbus arizonica');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SORARIlut', 'Sorbier/Alisier de l''Arizona (variété/cultivar ''lut'')', 'Sorbus arizonica ''lut''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SORAUC', 'Sorbier/Alisier des oiseleurs', 'Sorbus aucuparia');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SORDOM', 'Sorbier/Alisier commun', 'Sorbus domestica');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('SORTOR', 'Sorbier/Alisier', 'Sorbus (tor)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('TAMGAL', 'TAMGAL', 'TAM (gal)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('TAXBAC', 'If commun', 'Taxus baccata');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('TAXBACfas', 'If commun (port fastigié/colonnaire)', 'Taxus baccata f. fastigiata');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('TAXDIS', 'If', 'Taxus (dis)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('THUPLI', 'Thuya géant', 'Thuja plicata');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('THUPLIatr', 'Thuya géant (variété pourpre)', 'Thuja plicata f. purpurea/atropurpurea');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('THUPLIzeb', 'Thuya géant (variété/cultivar ''zeb'')', 'Thuja plicata ''zeb''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('TILCOR', 'Tilleul à petites feuilles (ou cordiforme)', 'Tilia cordata');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('TILCORgre', 'Tilleul à petites feuilles (ou cordiforme) (variété/cultivar ''gre'')', 'Tilia cordata ''gre''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('TILEUR', 'Tilleul', 'Tilia (eur)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('TILHEN', 'Tilleul', 'Tilia (hen)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('TILPLA', 'Tilleul plane', 'Tilia platanoides');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('TILTOM', 'Tilleul argenté', 'Tilia tomentosa');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ULMHOLlob', 'Orme (variété/cultivar ''lob'')', 'Ulmus (hol) ''lob''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ULMJAP', 'Orme du Japon', 'Ulmus japonica');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ULMMIN', 'Orme champêtre', 'Ulmus minor');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ULMREBnew', 'Orme (variété/cultivar ''new'')', 'Ulmus (reb) ''new''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ULMRES', 'Orme', 'Ulmus (res)');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ULMRESreb', 'Orme (variété/cultivar ''reb'')', 'Ulmus (res) ''reb''');
INSERT INTO especes (nom_code, nom_commun, nom_scientifique) VALUES ('ULMRESsap', 'Orme (variété/cultivar ''sap'')', 'Ulmus (res) ''sap''');
