version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bigdata_ia_web
    ports:
      - "3000:80"
    environment:
      - PYTHON_BIN=/opt/venv/bin/python3
      - DB_PATH=/var/www/html/data/trees.sqlite
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      # Volumes persistants pour la base de données et les journaux (logs)
      - app_data:/var/www/html/data
      - app_logs:/var/www/html/logs

volumes:
  # Définition des volumes nommés
  app_data:
  app_logs:
